name = "bolaojewale-homepage"
compatibility_date = "2024-09-23"

# Use nodejs_compat flag instead of node_compat
compatibility_flags = ["nodejs_compat"]

main = "dist/_worker.js"

[build]
command = "npm run build"

# Add KV namespace for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "4e0a079314c245b4a5e8c6b23a1e42a1"
preview_id = "77f45c81a4424647afab921b4786bd37"